project:
  type: website

website:
  title: "Portifólio em Ciência de Dados - Lucas Borges"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: Kaggle_Competition_2.ipynb
        text: Kaggle_Competition_2

format:
  html:
    theme: cosmo
    toc: true

